Итоговый пул
Blackdeer1524/TFL-1 pull request #4
Opened 2023-10-14 17:14 UTC by Blackdeer1524

2023-10-14 21:17 UTC, Blackdeer1524 commented
@TonitaN, я в итоге не выпиливал производную потому что слишком жалко :(

2023-10-15 22:05 UTC, TonitaN requested changes
Из критичного:
1. автомат Глушкова строится некорректно (лучше ещё раз просчитать алгоритм, чтобы результат совпадал с тем, который через First/Follow/Last)
2. потерялась проверка на эквивалентность исходной и трансформированной регулярки в модуле тестирования. Т.к. сейчас тестируются только заведомо не подходящие по словарю строки (нагрузочно, с накачкой) и результат их разбора очевидно будет у исходной и преобразованной регулярок одинаковым. Перед этим стоило проверить корректность преобразования на просто случайных путях в автомате Глушкова.
3. где-то в части Данилы регулярки меняют семантику. Пример: `(a|b*)`. Нужно разобраться с этим вопросом и протестировать после изменений на случайных регексах.

Если честно, часть Данилы уже смотрела не так внимательно (функция simplify написана довольно запутанно). В качестве благого пожелания - написать к ней комментарии. Все остальные мои заметки - тоже "для души". Не хочется выносить частичную дистрибутивность из альтернатив - ну и не надо, зачёт будет и без этого. Аналогично - с корректировкой порождения случайных регулярок в модуле Вячеслава.

2023-10-15 22:05 UTC, TonitaN commented on golang/internal/benchmark/benchmark.go
> +		wordsWithRegex.RegexBefore, okBefore, durBefore,
Golang, как минимум моя версия, довольно творчески выводит сообщения о времени, если не задать формат. Лучше добавить `Milliseconds` и выводить это как число.

2023-10-15 22:05 UTC, TonitaN commented on golang/internal/benchmark/benchmark.go
> +		<-time.After(time.Duration(len(words)) * time.Second)
Хотелось бы понять, зачем конвертировать в Duration длину тестирующего слова. Кажется, здесь я перестаю ориентироваться в коде.

2023-10-15 22:05 UTC, TonitaN commented on golang/internal/gluskov/tree_to_machine.go
> +		return 'я', 0
Это был эпсилон-переход? Очевидно, где-то проблема в конструкции: в Глушкове их не бывает. Из-за этого может обрушиться тестирование, ведь такие псевдо-эпсилоны попадут в тестирующую строку.

2023-10-15 22:05 UTC, TonitaN commented on golang/internal/gluskov/tree_to_machine.go
> +	leftState := m.handleRegex(node.Sub[0], currentState, false)
Почему финальность False? А если конкатенируемся со звездой?

2023-10-15 22:05 UTC, TonitaN commented on golang/internal/reggen/generator.go
> +		left := rgp.generateRegexRecursive(maxLength-1, maxStarHeight)
Вообще под длиной имелась в виду т.н. alphabetic width регулярок - совокупное число вхождений букв в регулярку. Но народ подходит к этому вопросу творчески, и здесь я вижу задание "длины максимального пути", причём примерно, из-за особенностей округления. Ну вот собственное понимание, что такое длина регулярки - в принципе, не страшно, округление - это мелкий баг, но не принципиальный в общем.  Равномерность длин аргументов конкатенации - баг чуть погрубее, с ним бы разобраться.

2023-10-15 22:05 UTC, TonitaN commented on golang/internal/wordgen/word_generator.go
> +		rww, err := GenerateWordsForRegex(regexes[i], countWords, maxDumpSize)
Хорошо бы логировать порождаемые слова в форме `x1 (x2)^n Z`, где `x2` --- область накачки, тогда бы, в том числе, стало видно псевдо-эпсилоны в порождаемых словах.

2023-10-15 22:05 UTC, TonitaN commented on golang/internal/gluskov/tree_to_machine.go
> +	case syntax.OpCharClass:
А вот это - насколько мне понятно, наследие импортируемого парсера, и не нужно было его обрабатывать - это ведь знак, что что-то пошло не так в регулярке.

2023-10-15 22:05 UTC, TonitaN commented on rust/src/aci.rs
> +                        let can_distribute = alt_args.iter().all(|item| match item {
Дистрибутивность же не обязана выносить общий множитель из всех скобок.
Может быть и так:
```
(a*a|b*|a*c) \\тут дистрибутивность у двух аргументов
```

2023-10-15 22:05 UTC, TonitaN commented on rust/src/parser.rs
> +        let after_ssnf = ssnf(res);
Почему народ помещает именно в парсер весь главный функционал? Вы не первые)

2023-10-15 22:05 UTC, TonitaN commented on rust/src/aci.rs
> +    match arg {
Если честно, то потерялась в этой функции. И непонятно, где именно нас настигла проблема: регулярка `(a|b*)` и подобные ей преобразуются некорректно. Я подозреваю, что дело всё же не в парсере, а в упрощениях, хотя не исключаю ничего.

2023-10-17 18:33 UTC, TonitaN commented
@Blackdeer1524 , теперь всё корректно, спасибо! Ждём исправления Славы.

2023-10-23 00:25 UTC, TonitaN requested changes
Эпсилоны в тестовых строках... :(
Простим баги генератора (генераторы почти никому не удались), и странное поведение парсера регулярок у Go. Но пока в тестовых строках есть явные эпсилоны, слишком очевидно, что с тестированием дело неладно.

2023-10-23 00:25 UTC, TonitaN commented on golang/internal/benchmark/benchmark.go
> +	regexes := reg.Generate()
В итоге получается два разных набора регулярок в разных системах тестов.

2023-10-23 00:25 UTC, TonitaN commented on golang/internal/reggen/generator.go
> +	regex := rgp.generateRegexRecursive(rgp.letterCount, rgp.alphabetSize)
😥

2023-10-23 00:25 UTC, TonitaN commented on golang/internal/reggen/generator.go
> +		return starKellie(subExpr)
Параметр звёздная высота - да кому я тут нужен?

2023-11-07 00:53 UTC, TonitaN approved these changes
Выглядит адекватно. Зачту.

2023-12-10 13:56 UTC, closed without merging